version: '3'
services:
  app:
    build:
      context: ../..
      dockerfile: ./.docker/dev/Dockerfile
    links:
      - database
    volumes:
      - /var/www/node_modules
    ports:
      - '3300:3300'
    env_file:
      - ./.env
    environment:
      PORT: 3300
      DEV_DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@database/$POSTGRES_DB
    depends_on:
      - database
  database:
    image: postgres:9.6-alpine
    expose:
      - '5432'
    ports:
      - '5433:5432'
    volumes:
      - umts_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 5
volumes:
  umts_data: